var express = require("express");
var router = express.Router();
var mongoose = require("mongoose");
var User = mongoose.model("User");
var passport = require("passport");




// --------------------- Big Board -----------------------------------

/* Get All Prospects */
router.post("/prospects", function(req, res, next) {
  User.findOne({username: req.body.username}).exec(function(err,result) {
    if(err) return next(err);
    res.send(result.prospects);
  });
});

/* Save Board */
router.post("/saveboard", function(req, res, next) {
  User.findOne({username: req.body.username}).exec(function(err,result) {
    if(err) return next(err);
    result.prospects = req.body.prospects;
    result.save(function(err, saved) {
      res.send(saved);
    });
  });
});



// --------------------- Sign Up -----------------------------------

/* Log In User */
router.post("/login", function(req, res, next) {
  passport.authenticate("local", function(err, user) {
    if(err) return next(err);
    res.send(user.createToken());
  })(req, res, next);
});

/* Register New User */
router.post("/register", function(req, res, next) {
  var user = new User(req.body);
  user.joined = new Date();
  user.setPassword(req.body.password);
  user.prospects = [
    {name: "Joey Bosa", position: "DE", height: "6-5", weight: 275, rank: 1, bbRank: 1, school: "Ohio State", img: "http://www.10tv.com/content/graphics/2014/10/02/4_Joey_Bosa.jpg", schImg: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/84/2013_Ohio_State_Buckeyes_logo.svg/1040px-2013_Ohio_State_Buckeyes_logo.svg.png",  bio: "One of the stars of Ohio State's National Title run in the 2014 season, Bosa was a top high school recruit out of high school and has lived up to that high billing, leading the Buckeyes with 21 tackles for loss and 13.5 sacks as a sophomore. He is still developing his pass rush sequence and how to best use his gifts, but he has all the traits to be a top pick in the 2016 class and disruptive presence in the NFL.", strengths: ["Physical At Line Of Scrimmage", "Great Play Awareness"], weaknesses: ["Needs To Shed Blocks Better", "Needs To Gain 20lbs", "Might Not Fit All Schemes"]},
    {name: "Laremy Tunsil", position: "OT", height: "6-5", weight: 305, rank: 1, bbRank: 2, school: "Ole Miss", img: "http://i1.wp.com/djournal.com/wp-content/blogs.dir/42/files/2014/11/Tunsil-Laremy.jpg", schImg: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/85/Ole_Miss_rebels_Logo.svg/2000px-Ole_Miss_rebels_Logo.svg.png",  bio: "On the field, Tunsil is a nimble big man with a rare athletic skill-set for the position, showing above average balance and flexibility to easily bend, handle speed and absorb power at the point of attack. He's not a perfect player, but his flaws are more nitpicking than true weaknesses and potential injuries are the only obstacles keeping Tunsil from being one of the better left tackles at the next level.", strengths: ["Good Size", "Great Balance", "Good Change of Direction"], weaknesses: ["Overeager at Times", "Injury Concerns", "Character Concerns"]},
    {name: "Jalen Ramsey", position: "CB", height: "6-1", weight: 202, rank: 1, bbRank: 3, school: "Florida State", img: "http://www.gannett-cdn.com/-mm-/a9c5875737dddec4a95332d330168466aecb1348/c=261-182-2053-2574&r=537&c=0-0-534-712/local/-/media/USATODAY/USATODAY/2014/08/10/1407719702000-2014-08-10-Jalen-Ramsey.jpg", schImg: "https://upload.wikimedia.org/wikipedia/en/thumb/c/c6/FSU_Seminoles.svg/1110px-FSU_Seminoles.svg.png",  bio: "Ramsey, who also plays a valuable role on special teams coverages, is a defensive savant with the framework that makes him a viable option at cornerback, safety or linebacker and if his 2015 tape matches or exceeds last year, he will be one of the top players drafted next spring.", strengths: ["Physical At Line Of Scrimmage", "Great Play Awareness"], weaknesses: ["Needs To Shed Blocks Better", "Needs To Gain 20lbs", "Might Not Fit All Schemes"]},
    {name: "Jared Goff", position: "QB", height: "6-4", weight: 210, rank: 1, bbRank: 4, school: "California", img: "http://www.mynfldraft.com/players/Jared%20Goff.jpg", schImg: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/17/University_of_California,_Berkeley_athletic_logo.svg/2000px-University_of_California,_Berkeley_athletic_logo.svg.png", bio: "Goff displays passing anticipation downfield, a resilient approach and coordinated feet in the pocket, which are always in sync with his body rhythm and allow him to reset his vision and find the open read. He clearly has room for improvement in several areas, but Goff is the type of quarterback who understands his deficiencies and what he needs to do in order to improve. And that's why scouts are optimistic for his future.", strengths: ["Physical At Line Of Scrimmage", "Great Play Awareness"], weaknesses: ["Needs To Shed Blocks Better", "Needs To Gain 20lbs", "Might Not Fit All Schemes"]},
    {name: "Myles Jack", position: "OLB", height: "6-1", weight: 245, rank: 1, bbRank: 5, school: "UCLA", img: "http://www.gannett-cdn.com/-mm-/9a27d9406e15a690b81d31bad07d23dae4e336fe/c=0-185-3280-2663&r=x404&c=534x401/local/-/media/USATODAY/USATODAY/2014/08/21/1408642298000-XXX-MYLES-JACK254-66581764.JPG", schImg: "https://upload.wikimedia.org/wikipedia/en/6/6d/UCLA_Bruins_Logo.png",  bio: "Out of this game due to a knee injury suffered in September which required season-ending surgery, Jack nonetheless projects as a top 15 pick, boasting perhaps the country's-best combination of instincts and athleticism. Unprecedented as the Pac-12 Offensive and Defensive Freshman of the Year in 2013, Jack has the vision, agility and speed to star at running back if he wanted to return to that position but is even more valuable on the defensive side of the ball, where he's a true three-down linebacker and future Pro Bowler.", strengths: ["Physical At Line Of Scrimmage", "Great Play Awareness"], weaknesses: ["Needs To Shed Blocks Better", "Needs To Gain 20lbs", "Might Not Fit All Schemes"]},
    {name: "Laquon Treadwell", position: "WR", height: "6-2", weight: 210, rank: 1, bbRank: 6, school: "Ole Miss", img: "http://www.thelocalvoice.net/oxford/wp-content/uploads/2014/10/LaquonTreadwellFEAT.jpg", schImg: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/85/Ole_Miss_rebels_Logo.svg/2000px-Ole_Miss_rebels_Logo.svg.png",  bio: "One of the stars of Ohio State's National Title run in the 2014 season, Bosa was a top high school recruit out of high school and has lived up to that high billing, leading the Buckeyes with 21 tackles for loss and 13.5 sacks as a sophomore. He is still developing his pass rush sequence and how to best use his gifts, but he has all the traits to be a top pick in the 2016 class and disruptive presence in the NFL.", strengths: ["Physical At Line Of Scrimmage", "Great Play Awareness"], weaknesses: ["Needs To Shed Blocks Better", "Needs To Gain 20lbs", "Might Not Fit All Schemes"]},
    {name: "Ronnie Stanley", position: "OT", height: "6-6", weight: 315, rank: 2, bbRank: 7, school: "Notre Dame", img: "http://www.elkharttruth.com/image/2014/08/31/800x800_b0/RStanley-jpg.jpg", schImg: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c7/NotreDameFightingIrish.svg/2000px-NotreDameFightingIrish.svg.png",  bio: "One of the stars of Ohio State's National Title run in the 2014 season, Bosa was a top high school recruit out of high school and has lived up to that high billing, leading the Buckeyes with 21 tackles for loss and 13.5 sacks as a sophomore. He is still developing his pass rush sequence and how to best use his gifts, but he has all the traits to be a top pick in the 2016 class and disruptive presence in the NFL.", strengths: ["Physical At Line Of Scrimmage", "Great Play Awareness"], weaknesses: ["Needs To Shed Blocks Better", "Needs To Gain 20lbs", "Might Not Fit All Schemes"]},
    {name: "DeForest Buckner", position: "DE", height: "6-7", weight: 290, rank: 2, bbRank: 8, school: "Oregon", img: "http://image.cdnllnwnl.xosnetwork.com/pics33/400/AP/APMDZZVWKSYGRPC.20140807003713.jpg", schImg: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7b/OregonDucks.svg/1243px-OregonDucks.svg.png",  bio: "One of the stars of Ohio State's National Title run in the 2014 season, Bosa was a top high school recruit out of high school and has lived up to that high billing, leading the Buckeyes with 21 tackles for loss and 13.5 sacks as a sophomore. He is still developing his pass rush sequence and how to best use his gifts, but he has all the traits to be a top pick in the 2016 class and disruptive presence in the NFL.", strengths: ["Physical At Line Of Scrimmage", "Great Play Awareness"], weaknesses: ["Needs To Shed Blocks Better", "Needs To Gain 20lbs", "Might Not Fit All Schemes"]},
    {name: "A'Shawn Robinson", position: "DT", height: "6-3", weight: 312, rank: 1, bbRank: 9, school: "Alabama", img: "http://www.star-telegram.com/sports/college/football/j0gbc8/picture34046538/ALTERNATES/FREE_640/A'Shawn%20alabama%202", schImg: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/61/Alabama_Crimson_Tide_Logo.svg/1000px-Alabama_Crimson_Tide_Logo.svg.png",  bio: "One of the stars of Ohio State's National Title run in the 2014 season, Bosa was a top high school recruit out of high school and has lived up to that high billing, leading the Buckeyes with 21 tackles for loss and 13.5 sacks as a sophomore. He is still developing his pass rush sequence and how to best use his gifts, but he has all the traits to be a top pick in the 2016 class and disruptive presence in the NFL.", strengths: ["Physical At Line Of Scrimmage", "Great Play Awareness"], weaknesses: ["Needs To Shed Blocks Better", "Needs To Gain 20lbs", "Might Not Fit All Schemes"]},
    {name: "Mackensie Alexander", position: "CB", height: "5-10", weight: 195, rank: 2, bbRank: 10, school: "Clemson", img: "https://pbs.twimg.com/profile_images/460244114156421122/02vMgmt1.jpeg", schImg: "http://www.clemson.edu/administration/public-affairs/toolbox/downloads/logos/logos/paw.gif",  bio: "One of the stars of Ohio State's National Title run in the 2014 season, Bosa was a top high school recruit out of high school and has lived up to that high billing, leading the Buckeyes with 21 tackles for loss and 13.5 sacks as a sophomore. He is still developing his pass rush sequence and how to best use his gifts, but he has all the traits to be a top pick in the 2016 class and disruptive presence in the NFL.", strengths: ["Physical At Line Of Scrimmage", "Great Play Awareness"], weaknesses: ["Needs To Shed Blocks Better", "Needs To Gain 20lbs", "Might Not Fit All Schemes"]},
    {name: "Carson Wentz", position: "QB", height: "6-5", weight: 231, rank: 2, bbRank: 11, school: "North Dakota State", img: "http://binaryapi.ap.org/80af0089ec124cb8a1d99c21be60e7b0/460x.jpg", schImg: "http://cdn.mastersinpsychologyguide.com/uploads/school/logo/2991/NDSU.jpg",  bio: "One of the stars of Ohio State's National Title run in the 2014 season, Bosa was a top high school recruit out of high school and has lived up to that high billing, leading the Buckeyes with 21 tackles for loss and 13.5 sacks as a sophomore. He is still developing his pass rush sequence and how to best use his gifts, but he has all the traits to be a top pick in the 2016 class and disruptive presence in the NFL.", strengths: ["Physical At Line Of Scrimmage", "Great Play Awareness"], weaknesses: ["Needs To Shed Blocks Better", "Needs To Gain 20lbs", "Might Not Fit All Schemes"]},
    {name: "Shaq Lawson", position: "DE", height: "6-3", weight: 270, rank: 3, bbRank: 12, school: "Clemson", img: "http://media.jrn.com/images/0412_dmsp_spring_game_shaq_lawson_3_1429970473215_17306129_ver1.0_640_480.jpg", schImg: "http://www.clemson.edu/administration/public-affairs/toolbox/downloads/logos/logos/paw.gif",  bio: "One of the stars of Ohio State's National Title run in the 2014 season, Bosa was a top high school recruit out of high school and has lived up to that high billing, leading the Buckeyes with 21 tackles for loss and 13.5 sacks as a sophomore. He is still developing his pass rush sequence and how to best use his gifts, but he has all the traits to be a top pick in the 2016 class and disruptive presence in the NFL.", strengths: ["Physical At Line Of Scrimmage", "Great Play Awareness"], weaknesses: ["Needs To Shed Blocks Better", "Needs To Gain 20lbs", "Might Not Fit All Schemes"]},
    {name: "Ezekiel Elliott", position: "RB", height: "6-0", weight: 225, rank: 1, bbRank: 13, school: "Ohio State", img: "http://ll-media.tmz.com/2015/12/28/1228-ezekiel-elliott-getty-01-1200x630.jpg", schImg: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/84/2013_Ohio_State_Buckeyes_logo.svg/1040px-2013_Ohio_State_Buckeyes_logo.svg.png",  bio: "One of the stars of Ohio State's National Title run in the 2014 season, Bosa was a top high school recruit out of high school and has lived up to that high billing, leading the Buckeyes with 21 tackles for loss and 13.5 sacks as a sophomore. He is still developing his pass rush sequence and how to best use his gifts, but he has all the traits to be a top pick in the 2016 class and disruptive presence in the NFL.", strengths: ["Physical At Line Of Scrimmage", "Great Play Awareness"], weaknesses: ["Needs To Shed Blocks Better", "Needs To Gain 20lbs", "Might Not Fit All Schemes"]},
    {name: "Vernon Hargreaves III", position: "CB", height: "5-11", weight: 199, rank: 3, bbRank: 14, school: "Florida", img: "http://www.trbimg.com/img-566f5564/turbine/os-gators-vernon-hargreaves-iii-all-america-20151214", schImg: "https://upload.wikimedia.org/wikipedia/en/thumb/1/12/Florida_Gators_logo.svg/470px-Florida_Gators_logo.svg.png",  bio: "One of the stars of Ohio State's National Title run in the 2014 season, Bosa was a top high school recruit out of high school and has lived up to that high billing, leading the Buckeyes with 21 tackles for loss and 13.5 sacks as a sophomore. He is still developing his pass rush sequence and how to best use his gifts, but he has all the traits to be a top pick in the 2016 class and disruptive presence in the NFL.", strengths: ["Physical At Line Of Scrimmage", "Great Play Awareness"], weaknesses: ["Needs To Shed Blocks Better", "Needs To Gain 20lbs", "Might Not Fit All Schemes"]},
    {name: "Andrew Billings", position: "DT", height: "6-1", weight: 310, rank: 2, bbRank: 15, school: "Baylor", img: "http://imgix.scout.com/155/1557140.jpg?w=620&h=413&fit=max", schImg: "http://vector.me/files/images/2/8/28169/baylor_bears.png",  bio: "One of the stars of Ohio State's National Title run in the 2014 season, Bosa was a top high school recruit out of high school and has lived up to that high billing, leading the Buckeyes with 21 tackles for loss and 13.5 sacks as a sophomore. He is still developing his pass rush sequence and how to best use his gifts, but he has all the traits to be a top pick in the 2016 class and disruptive presence in the NFL.", strengths: ["Physical At Line Of Scrimmage", "Great Play Awareness"], weaknesses: ["Needs To Shed Blocks Better", "Needs To Gain 20lbs", "Might Not Fit All Schemes"]},
    {name: "Reggie Ragland", position: "ILB", height: "6-2", weight: 252, rank: 1, bbRank: 16, school: "Alabama", img: "https://localtvwhnt.files.wordpress.com/2015/07/ragland4.jpeg?w=1200", schImg: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/61/Alabama_Crimson_Tide_Logo.svg/1000px-Alabama_Crimson_Tide_Logo.svg.png",  bio: "One of the stars of Ohio State's National Title run in the 2014 season, Bosa was a top high school recruit out of high school and has lived up to that high billing, leading the Buckeyes with 21 tackles for loss and 13.5 sacks as a sophomore. He is still developing his pass rush sequence and how to best use his gifts, but he has all the traits to be a top pick in the 2016 class and disruptive presence in the NFL.", strengths: ["Physical At Line Of Scrimmage", "Great Play Awareness"], weaknesses: ["Needs To Shed Blocks Better", "Needs To Gain 20lbs", "Might Not Fit All Schemes"]},
    {name: "Paxton Lynch", position: "QB", height: "6-6", weight: 230, rank: 3, bbRank: 17, school: "Memphis", img: "http://media1.fdncms.com/memphisflyer/imager/paxton-lynch/u/original/3781759/1416179395-lynch14.jpg", schImg: "https://upload.wikimedia.org/wikipedia/en/thumb/3/34/MemphisTigers.svg/1175px-MemphisTigers.svg.png",  bio: "One of the stars of Ohio State's National Title run in the 2014 season, Bosa was a top high school recruit out of high school and has lived up to that high billing, leading the Buckeyes with 21 tackles for loss and 13.5 sacks as a sophomore. He is still developing his pass rush sequence and how to best use his gifts, but he has all the traits to be a top pick in the 2016 class and disruptive presence in the NFL.", strengths: ["Physical At Line Of Scrimmage", "Great Play Awareness"], weaknesses: ["Needs To Shed Blocks Better", "Needs To Gain 20lbs", "Might Not Fit All Schemes"]},
    {name: "Darron Lee", position: "OLB", height: "6-1", weight: 235, rank: 2, bbRank: 18, school: "Ohio State", img: "http://www.elevenwarriors.com/sites/default/files/styles/904x490/public/c/2014/09/39671_h.jpg?itok=LEKmKOtQ", schImg: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/84/2013_Ohio_State_Buckeyes_logo.svg/1040px-2013_Ohio_State_Buckeyes_logo.svg.png",  bio: "One of the stars of Ohio State's National Title run in the 2014 season, Bosa was a top high school recruit out of high school and has lived up to that high billing, leading the Buckeyes with 21 tackles for loss and 13.5 sacks as a sophomore. He is still developing his pass rush sequence and how to best use his gifts, but he has all the traits to be a top pick in the 2016 class and disruptive presence in the NFL.", strengths: ["Physical At Line Of Scrimmage", "Great Play Awareness"], weaknesses: ["Needs To Shed Blocks Better", "Needs To Gain 20lbs", "Might Not Fit All Schemes"]},
    {name: "Robert Nkemdiche", position: "DT", height: "6-3", weight: 296, rank: 3, bbRank: 19, school: "Ole Miss", img: "http://images.hngn.com/data/images/full/174519/ole-miss-defensive-lineman-robert-nkemdiche.jpg?w=650", schImg: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/85/Ole_Miss_rebels_Logo.svg/2000px-Ole_Miss_rebels_Logo.svg.png",  bio: "One of the stars of Ohio State's National Title run in the 2014 season, Bosa was a top high school recruit out of high school and has lived up to that high billing, leading the Buckeyes with 21 tackles for loss and 13.5 sacks as a sophomore. He is still developing his pass rush sequence and how to best use his gifts, but he has all the traits to be a top pick in the 2016 class and disruptive presence in the NFL.", strengths: ["Physical At Line Of Scrimmage", "Great Play Awareness"], weaknesses: ["Needs To Shed Blocks Better", "Needs To Gain 20lbs", "Might Not Fit All Schemes"]},
    {name: "Taylor Decker", position: "OT", height: "6-7", weight: 315, rank: 3, bbRank: 20, school: "Ohio State", img: "http://www.dispatch.com/content/graphics/2014/12/29/osufb-12-29-art-gj0vpj45-1osufb-12-29-eq-22.jpg", schImg: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/84/2013_Ohio_State_Buckeyes_logo.svg/1040px-2013_Ohio_State_Buckeyes_logo.svg.png",  bio: "One of the stars of Ohio State's National Title run in the 2014 season, Bosa was a top high school recruit out of high school and has lived up to that high billing, leading the Buckeyes with 21 tackles for loss and 13.5 sacks as a sophomore. He is still developing his pass rush sequence and how to best use his gifts, but he has all the traits to be a top pick in the 2016 class and disruptive presence in the NFL.", strengths: ["Physical At Line Of Scrimmage", "Great Play Awareness"], weaknesses: ["Needs To Shed Blocks Better", "Needs To Gain 20lbs", "Might Not Fit All Schemes"]},
    {name: "Leonard Floyd", position: "OLB", height: "6-3", weight: 232, rank: 3, bbRank: 21, school: "Georgia", img: "http://www.saturdaydownsouth.com/wp-content/uploads/2016/01/USATSI_8942889_168381178_lowres-650x342.jpg", schImg: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5b/UGA_logo.svg/1280px-UGA_logo.svg.png",  bio: "One of the stars of Ohio State's National Title run in the 2014 season, Bosa was a top high school recruit out of high school and has lived up to that high billing, leading the Buckeyes with 21 tackles for loss and 13.5 sacks as a sophomore. He is still developing his pass rush sequence and how to best use his gifts, but he has all the traits to be a top pick in the 2016 class and disruptive presence in the NFL.", strengths: ["Physical At Line Of Scrimmage", "Great Play Awareness"], weaknesses: ["Needs To Shed Blocks Better", "Needs To Gain 20lbs", "Might Not Fit All Schemes"]},
    {name: "Jonathan Bullard", position: "DE", height: "6-3", weight: 283, rank: 4, bbRank: 22, school: "Florida", img: "http://www.saturdaydownsouth.com/wp-content/uploads/2014/11/USATSI_7581548-650x342.jpg", schImg: "https://upload.wikimedia.org/wikipedia/en/thumb/1/12/Florida_Gators_logo.svg/470px-Florida_Gators_logo.svg.png",  bio: "One of the stars of Ohio State's National Title run in the 2014 season, Bosa was a top high school recruit out of high school and has lived up to that high billing, leading the Buckeyes with 21 tackles for loss and 13.5 sacks as a sophomore. He is still developing his pass rush sequence and how to best use his gifts, but he has all the traits to be a top pick in the 2016 class and disruptive presence in the NFL.", strengths: ["Physical At Line Of Scrimmage", "Great Play Awareness"], weaknesses: ["Needs To Shed Blocks Better", "Needs To Gain 20lbs", "Might Not Fit All Schemes"]},
    {name: "Jarran Reed", position: "DT", height: "6-3", weight: 313, rank: 4, bbRank: 23, school: "Alabama", img: "http://athlonsports.com/sites/athlonsports.com/files/1455888_0.jpg", schImg: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/61/Alabama_Crimson_Tide_Logo.svg/1000px-Alabama_Crimson_Tide_Logo.svg.png",  bio: "One of the stars of Ohio State's National Title run in the 2014 season, Bosa was a top high school recruit out of high school and has lived up to that high billing, leading the Buckeyes with 21 tackles for loss and 13.5 sacks as a sophomore. He is still developing his pass rush sequence and how to best use his gifts, but he has all the traits to be a top pick in the 2016 class and disruptive presence in the NFL.", strengths: ["Physical At Line Of Scrimmage", "Great Play Awareness"], weaknesses: ["Needs To Shed Blocks Better", "Needs To Gain 20lbs", "Might Not Fit All Schemes"]},
    {name: "Corey Coleman", position: "WR", height: "5-10", weight: 190, rank: 2, bbRank: 24, school: "Baylor", img: "https://cmgstatesmancollegesports.files.wordpress.com/2015/12/494100448-corey-coleman-of-the-baylor-bears-celebrates-gettyimages.jpg?w=640", schImg: "http://vector.me/files/images/2/8/28169/baylor_bears.png",  bio: "One of the stars of Ohio State's National Title run in the 2014 season, Bosa was a top high school recruit out of high school and has lived up to that high billing, leading the Buckeyes with 21 tackles for loss and 13.5 sacks as a sophomore. He is still developing his pass rush sequence and how to best use his gifts, but he has all the traits to be a top pick in the 2016 class and disruptive presence in the NFL.", strengths: ["Physical At Line Of Scrimmage", "Great Play Awareness"], weaknesses: ["Needs To Shed Blocks Better", "Needs To Gain 20lbs", "Might Not Fit All Schemes"]},
    {name: "Jack Conklin", position: "OT", height: "6-6", weight: 318, rank: 4, bbRank: 25, school: "Michigan State", img: "http://www.gannett-cdn.com/-mm-/957bb3e62ac49855480f17230df06b304dd5fce6/c=2-0-386-512&r=537&c=0-0-534-712/local/-/media/2015/05/07/DetroitFreePress/DetroitFreePress/635666058777288678-jack.JPG", schImg: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/af/Michigan-State-logo-block-s.svg/2000px-Michigan-State-logo-block-s.svg.png",  bio: "One of the stars of Ohio State's National Title run in the 2014 season, Bosa was a top high school recruit out of high school and has lived up to that high billing, leading the Buckeyes with 21 tackles for loss and 13.5 sacks as a sophomore. He is still developing his pass rush sequence and how to best use his gifts, but he has all the traits to be a top pick in the 2016 class and disruptive presence in the NFL.", strengths: ["Physical At Line Of Scrimmage", "Great Play Awareness"], weaknesses: ["Needs To Shed Blocks Better", "Needs To Gain 20lbs", "Might Not Fit All Schemes"]},
    {name: "Emmanuel Ogbah", position: "DE", height: "6-3", weight: 275, rank: 5, bbRank: 26, school: "Oklahoma State", img: "http://www.gannett-cdn.com/-mm-/51408541b3fdd292d9d9092135e6b5a9c7f8ea39/c=487-0-4254-2832&r=x408&c=540x405/local/-/media/2015/10/28/USATODAY/USATODAY/635816447285800560-AP-KANSAS-ST-OKLAHOMA-ST-FOOTBALL-76549276.JPG", schImg: "https://upload.wikimedia.org/wikipedia/en/f/f2/Osu_ath_brand.png",  bio: "One of the stars of Ohio State's National Title run in the 2014 season, Bosa was a top high school recruit out of high school and has lived up to that high billing, leading the Buckeyes with 21 tackles for loss and 13.5 sacks as a sophomore. He is still developing his pass rush sequence and how to best use his gifts, but he has all the traits to be a top pick in the 2016 class and disruptive presence in the NFL.", strengths: ["Physical At Line Of Scrimmage", "Great Play Awareness"], weaknesses: ["Needs To Shed Blocks Better", "Needs To Gain 20lbs", "Might Not Fit All Schemes"]},
    {name: "Jaylon Smith", position: "OLB", height: "6-3", weight: 240, rank: 4, bbRank: 27, school: "Notre Dame", img: "http://www.uhnd.com/wp-content/uploads/2014/09/jaylon-smith-purdue.jpg", schImg: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c7/NotreDameFightingIrish.svg/2000px-NotreDameFightingIrish.svg.png",  bio: "One of the stars of Ohio State's National Title run in the 2014 season, Bosa was a top high school recruit out of high school and has lived up to that high billing, leading the Buckeyes with 21 tackles for loss and 13.5 sacks as a sophomore. He is still developing his pass rush sequence and how to best use his gifts, but he has all the traits to be a top pick in the 2016 class and disruptive presence in the NFL.", strengths: ["Physical At Line Of Scrimmage", "Great Play Awareness"], weaknesses: ["Needs To Shed Blocks Better", "Needs To Gain 20lbs", "Might Not Fit All Schemes"]},
    {name: "Connor Cook", position: "QB", height: "6-4", weight: 220, rank: 4, bbRank: 28, school: "Michigan State", img: "http://s3media.247sports.com/Uploads/Assets/301/186/6_3186301.JPG", schImg: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/af/Michigan-State-logo-block-s.svg/2000px-Michigan-State-logo-block-s.svg.png",  bio: "One of the stars of Ohio State's National Title run in the 2014 season, Bosa was a top high school recruit out of high school and has lived up to that high billing, leading the Buckeyes with 21 tackles for loss and 13.5 sacks as a sophomore. He is still developing his pass rush sequence and how to best use his gifts, but he has all the traits to be a top pick in the 2016 class and disruptive presence in the NFL.", strengths: ["Physical At Line Of Scrimmage", "Great Play Awareness"], weaknesses: ["Needs To Shed Blocks Better", "Needs To Gain 20lbs", "Might Not Fit All Schemes"]},
    {name: "Noah Spence", position: "OLB", height: "6-3", weight: 254, rank: 5, bbRank: 29, school: "Eastern Kentucky", img: "http://www.kentucky.com/sports/college/football/z6twi7/picture49298865/ALTERNATES/FREE_320/Noah%20Spence%20(2015)", schImg: "http://kyean.org/wp-content/uploads/2015/01/EKU-Logo-large_transparent.png",  bio: "One of the stars of Ohio State's National Title run in the 2014 season, Bosa was a top high school recruit out of high school and has lived up to that high billing, leading the Buckeyes with 21 tackles for loss and 13.5 sacks as a sophomore. He is still developing his pass rush sequence and how to best use his gifts, but he has all the traits to be a top pick in the 2016 class and disruptive presence in the NFL.", strengths: ["Physical At Line Of Scrimmage", "Great Play Awareness"], weaknesses: ["Needs To Shed Blocks Better", "Needs To Gain 20lbs", "Might Not Fit All Schemes"]},
    {name: "Kenny Clark", position: "DT", height: "6-2", weight: 310, rank: 5, bbRank: 30, school: "UCLA", img: "http://larrybrownsports.com/wp-content/uploads/2015/12/kenny-clark-ucla-560x373.jpg", schImg: "https://upload.wikimedia.org/wikipedia/en/6/6d/UCLA_Bruins_Logo.png",  bio: "One of the stars of Ohio State's National Title run in the 2014 season, Bosa was a top high school recruit out of high school and has lived up to that high billing, leading the Buckeyes with 21 tackles for loss and 13.5 sacks as a sophomore. He is still developing his pass rush sequence and how to best use his gifts, but he has all the traits to be a top pick in the 2016 class and disruptive presence in the NFL.", strengths: ["Physical At Line Of Scrimmage", "Great Play Awareness"], weaknesses: ["Needs To Shed Blocks Better", "Needs To Gain 20lbs", "Might Not Fit All Schemes"]},
    {name: "Kevin Dodd", position: "DE", height: "6-4", weight: 275, rank: 6, bbRank: 31, school: "Clemson", img: "http://i3.tigernet.com/stories/15/football/Dodd_Kevin_practice_700.jpg", schImg: "http://www.clemson.edu/administration/public-affairs/toolbox/downloads/logos/logos/paw.gif",  bio: "One of the stars of Ohio State's National Title run in the 2014 season, Bosa was a top high school recruit out of high school and has lived up to that high billing, leading the Buckeyes with 21 tackles for loss and 13.5 sacks as a sophomore. He is still developing his pass rush sequence and how to best use his gifts, but he has all the traits to be a top pick in the 2016 class and disruptive presence in the NFL.", strengths: ["Physical At Line Of Scrimmage", "Great Play Awareness"], weaknesses: ["Needs To Shed Blocks Better", "Needs To Gain 20lbs", "Might Not Fit All Schemes"]},
    {name: "Eli Apple", position: "CB", height: "6-1", weight: 200, rank: 4, bbRank: 32, school: "Ohio State", img: "http://www4.pictures.zimbio.com/gi/Western+Michigan+v+Ohio+State+Lb6RKarVodEl.jpg", schImg: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/84/2013_Ohio_State_Buckeyes_logo.svg/1040px-2013_Ohio_State_Buckeyes_logo.svg.png",  bio: "One of the stars of Ohio State's National Title run in the 2014 season, Bosa was a top high school recruit out of high school and has lived up to that high billing, leading the Buckeyes with 21 tackles for loss and 13.5 sacks as a sophomore. He is still developing his pass rush sequence and how to best use his gifts, but he has all the traits to be a top pick in the 2016 class and disruptive presence in the NFL.", strengths: ["Physical At Line Of Scrimmage", "Great Play Awareness"], weaknesses: ["Needs To Shed Blocks Better", "Needs To Gain 20lbs", "Might Not Fit All Schemes"]},
    {name: "Shon Coleman", position: "OT", height: "6-6", weight: 313, rank: 5, bbRank: 33, school: "Auburn", img: "http://image.al.com/home/bama-media/width620/img/auburnfootball_impact/photo/15728275-mmmain.jpg", schImg: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/bb/Auburn_University_Athletics_logo.svg/2000px-Auburn_University_Athletics_logo.svg.png",  bio: "One of the stars of Ohio State's National Title run in the 2014 season, Bosa was a top high school recruit out of high school and has lived up to that high billing, leading the Buckeyes with 21 tackles for loss and 13.5 sacks as a sophomore. He is still developing his pass rush sequence and how to best use his gifts, but he has all the traits to be a top pick in the 2016 class and disruptive presence in the NFL.", strengths: ["Physical At Line Of Scrimmage", "Great Play Awareness"], weaknesses: ["Needs To Shed Blocks Better", "Needs To Gain 20lbs", "Might Not Fit All Schemes"]},
    {name: "Hunter Henry", position: "TE", height: "6-5", weight: 253, rank: 1, bbRank: 34, school: "Arkansas", img: "http://media.arkansasonline.com/img/photos/2013/08/30/Arkansas_Razorbacks_FBC_med-2_r600x400.jpg?689b03237e9432d372b8e4e059d8b6cfaff1b604", schImg: "http://pictures.dealer.com/l/littlerockcdjcllc/0351/17a6364e74f5c476bfad20ff29bc9c46x.jpg",  bio: "One of the stars of Ohio State's National Title run in the 2014 season, Bosa was a top high school recruit out of high school and has lived up to that high billing, leading the Buckeyes with 21 tackles for loss and 13.5 sacks as a sophomore. He is still developing his pass rush sequence and how to best use his gifts, but he has all the traits to be a top pick in the 2016 class and disruptive presence in the NFL.", strengths: ["Physical At Line Of Scrimmage", "Great Play Awareness"], weaknesses: ["Needs To Shed Blocks Better", "Needs To Gain 20lbs", "Might Not Fit All Schemes"]},
    {name: "Michael Thomas", position: "WR", height: "6-3", weight: 210, rank: 3, bbRank: 35, school: "Ohio State", img: "http://cdn.fansided.com/wp-content/blogs.dir/25/files/2015/12/michael-thomas-ncaa-football-ohio-state-michigan-850x560.jpg", schImg: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/84/2013_Ohio_State_Buckeyes_logo.svg/1040px-2013_Ohio_State_Buckeyes_logo.svg.png",  bio: "One of the stars of Ohio State's National Title run in the 2014 season, Bosa was a top high school recruit out of high school and has lived up to that high billing, leading the Buckeyes with 21 tackles for loss and 13.5 sacks as a sophomore. He is still developing his pass rush sequence and how to best use his gifts, but he has all the traits to be a top pick in the 2016 class and disruptive presence in the NFL.", strengths: ["Physical At Line Of Scrimmage", "Great Play Awareness"], weaknesses: ["Needs To Shed Blocks Better", "Needs To Gain 20lbs", "Might Not Fit All Schemes"]},
    {name: "Sheldon Rankins", position: "DT", height: "6-2", weight: 304, rank: 6, bbRank: 36, school: "Louisville", img: "http://imgix.scout.com/136/1367037.jpg", schImg: "http://a1.espncdn.com/combiner/i?img=%2Fi%2Fteamlogos%2Fncaa%2F500%2F97.png",  bio: "One of the stars of Ohio State's National Title run in the 2014 season, Bosa was a top high school recruit out of high school and has lived up to that high billing, leading the Buckeyes with 21 tackles for loss and 13.5 sacks as a sophomore. He is still developing his pass rush sequence and how to best use his gifts, but he has all the traits to be a top pick in the 2016 class and disruptive presence in the NFL.", strengths: ["Physical At Line Of Scrimmage", "Great Play Awareness"], weaknesses: ["Needs To Shed Blocks Better", "Needs To Gain 20lbs", "Might Not Fit All Schemes"]},
    {name: "Josh Doctson", position: "WR", height: "6-2", weight: 195, rank: 4, bbRank: 37, school: "TCU", img: "http://i.turner.ncaa.com/sites/default/files/styles/640x360/public/media/usatsi_8899737.jpg?itok=HmQ1EzD3", schImg: "https://upload.wikimedia.org/wikipedia/en/thumb/6/6e/TCU_Horned_Frogs_Logo.svg/1280px-TCU_Horned_Frogs_Logo.svg.png",  bio: "One of the stars of Ohio State's National Title run in the 2014 season, Bosa was a top high school recruit out of high school and has lived up to that high billing, leading the Buckeyes with 21 tackles for loss and 13.5 sacks as a sophomore. He is still developing his pass rush sequence and how to best use his gifts, but he has all the traits to be a top pick in the 2016 class and disruptive presence in the NFL.", strengths: ["Physical At Line Of Scrimmage", "Great Play Awareness"], weaknesses: ["Needs To Shed Blocks Better", "Needs To Gain 20lbs", "Might Not Fit All Schemes"]},
    {name: "Ryan Kelly", position: "C ", height: "6-4", weight: 297, rank: 1, bbRank: 38, school: "Alabama", img: "http://www.gannett-cdn.com/-mm-/e8abbc34b185e5ee3a1960c1da21156dc172b70d/c=20-0-3566-2666&r=x404&c=534x401/local/-/media/2014/12/30/Cincinnati/Cincinnati/635555418502367109-USATSI-8216412.jpg", schImg: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/61/Alabama_Crimson_Tide_Logo.svg/1000px-Alabama_Crimson_Tide_Logo.svg.png",  bio: "One of the stars of Ohio State's National Title run in the 2014 season, Bosa was a top high school recruit out of high school and has lived up to that high billing, leading the Buckeyes with 21 tackles for loss and 13.5 sacks as a sophomore. He is still developing his pass rush sequence and how to best use his gifts, but he has all the traits to be a top pick in the 2016 class and disruptive presence in the NFL.", strengths: ["Physical At Line Of Scrimmage", "Great Play Awareness"], weaknesses: ["Needs To Shed Blocks Better", "Needs To Gain 20lbs", "Might Not Fit All Schemes"]},
    {name: "Derrick Henry", position: "RB", height: "6-2", weight: 242, rank: 2, bbRank: 39, school: "Alabama", img: "http://media.al.com/alabamafootball_impact/photo/1214henryhairjpg-42acf72d657c87b0.jpg", schImg: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/61/Alabama_Crimson_Tide_Logo.svg/1000px-Alabama_Crimson_Tide_Logo.svg.png",  bio: "One of the stars of Ohio State's National Title run in the 2014 season, Bosa was a top high school recruit out of high school and has lived up to that high billing, leading the Buckeyes with 21 tackles for loss and 13.5 sacks as a sophomore. He is still developing his pass rush sequence and how to best use his gifts, but he has all the traits to be a top pick in the 2016 class and disruptive presence in the NFL.", strengths: ["Physical At Line Of Scrimmage", "Great Play Awareness"], weaknesses: ["Needs To Shed Blocks Better", "Needs To Gain 20lbs", "Might Not Fit All Schemes"]},
    {name: "Germain Ifedi", position: "OT", height: "6-5", weight: 325, rank: 6, bbRank: 40, school: "Texas A&M", img: "https://cmgstatesmancollegesports.files.wordpress.com/2016/01/465678749-germain-ifedi-of-the-texas-a-m-aggies-looks-gettyimages.jpg?w=640", schImg: "http://brandguide.tamu.edu/downloads/logos/TAMU-logos-rgb/TAM-Logo/TAM-Logo.png",  bio: "One of the stars of Ohio State's National Title run in the 2014 season, Bosa was a top high school recruit out of high school and has lived up to that high billing, leading the Buckeyes with 21 tackles for loss and 13.5 sacks as a sophomore. He is still developing his pass rush sequence and how to best use his gifts, but he has all the traits to be a top pick in the 2016 class and disruptive presence in the NFL.", strengths: ["Physical At Line Of Scrimmage", "Great Play Awareness"], weaknesses: ["Needs To Shed Blocks Better", "Needs To Gain 20lbs", "Might Not Fit All Schemes"]},
    {name: "Will Fuller", position: "WR", height: "6-0", weight: 184, rank: 5, bbRank: 41, school: "Notre Dame", img: "http://img.scout.com/sites/default/files/2015/12/11/fuller_t1031_30_1280.jpg?w=620&h=413&fit=max", schImg: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c7/NotreDameFightingIrish.svg/2000px-NotreDameFightingIrish.svg.png",  bio: "One of the stars of Ohio State's National Title run in the 2014 season, Bosa was a top high school recruit out of high school and has lived up to that high billing, leading the Buckeyes with 21 tackles for loss and 13.5 sacks as a sophomore. He is still developing his pass rush sequence and how to best use his gifts, but he has all the traits to be a top pick in the 2016 class and disruptive presence in the NFL.", strengths: ["Physical At Line Of Scrimmage", "Great Play Awareness"], weaknesses: ["Needs To Shed Blocks Better", "Needs To Gain 20lbs", "Might Not Fit All Schemes"]},
    {name: "Jason Spriggs", position: "OT", height: "6-6", weight: 301, rank: 7, bbRank: 42, school: "Indiana", img: "http://imgix.scout.com/141/1414110.jpg?w=600&h=360&fit=max", schImg: "http://logonoid.com/images/indiana-hoosiers-logo.png",  bio: "One of the stars of Ohio State's National Title run in the 2014 season, Bosa was a top high school recruit out of high school and has lived up to that high billing, leading the Buckeyes with 21 tackles for loss and 13.5 sacks as a sophomore. He is still developing his pass rush sequence and how to best use his gifts, but he has all the traits to be a top pick in the 2016 class and disruptive presence in the NFL.", strengths: ["Physical At Line Of Scrimmage", "Great Play Awareness"], weaknesses: ["Needs To Shed Blocks Better", "Needs To Gain 20lbs", "Might Not Fit All Schemes"]},
    {name: "Kendall Fuller", position: "CB", height: "6-0", weight: 197, rank: 5, bbRank: 43, school: "Virginia Tech", img: "http://cdn.fansided.com/wp-content/blogs.dir/233/files/2014/07/kendall-fuller-ncaa-football-duke-virginia-tech1-850x560.jpg", schImg: "http://static1.squarespace.com/static/564deba6e4b012548e36c2a0/56821d6869a91ad70f5e57d2/568ebfa740667aa206d71851/1452195752074/vt+vector.png",  bio: "One of the stars of Ohio State's National Title run in the 2014 season, Bosa was a top high school recruit out of high school and has lived up to that high billing, leading the Buckeyes with 21 tackles for loss and 13.5 sacks as a sophomore. He is still developing his pass rush sequence and how to best use his gifts, but he has all the traits to be a top pick in the 2016 class and disruptive presence in the NFL.", strengths: ["Physical At Line Of Scrimmage", "Great Play Awareness"], weaknesses: ["Needs To Shed Blocks Better", "Needs To Gain 20lbs", "Might Not Fit All Schemes"]},
    {name: "Cody Whitehair", position: "OG", height: "6-4", weight: 300, rank: 1, bbRank: 44, school: "Kansas State", img: "http://www.kansascity.com/sports/college/big-12/kansas-state/dw9qnr/picture29535787/ALTERNATES/FREE_640/codywhitehair", schImg: "http://www.printyourbrackets.com/ncaa-logos/kansas-state-wildcats-logo.png",  bio: "One of the stars of Ohio State's National Title run in the 2014 season, Bosa was a top high school recruit out of high school and has lived up to that high billing, leading the Buckeyes with 21 tackles for loss and 13.5 sacks as a sophomore. He is still developing his pass rush sequence and how to best use his gifts, but he has all the traits to be a top pick in the 2016 class and disruptive presence in the NFL.", strengths: ["Physical At Line Of Scrimmage", "Great Play Awareness"], weaknesses: ["Needs To Shed Blocks Better", "Needs To Gain 20lbs", "Might Not Fit All Schemes"]},
    {name: "Austin Johnson", position: "DT", height: "6-4", weight: 323, rank: 7, bbRank: 45, school: "Penn State", img: "http://www.post-gazette.com/image/2014/08/31/ca580,173,1392,986/psu0901a.jpg", schImg: "http://vignette3.wikia.nocookie.net/logopedia/images/1/10/500px-Penn_State_Nittany_Lions_svg.png/revision/latest?cb=20130523234101",  bio: "One of the stars of Ohio State's National Title run in the 2014 season, Bosa was a top high school recruit out of high school and has lived up to that high billing, leading the Buckeyes with 21 tackles for loss and 13.5 sacks as a sophomore. He is still developing his pass rush sequence and how to best use his gifts, but he has all the traits to be a top pick in the 2016 class and disruptive presence in the NFL.", strengths: ["Physical At Line Of Scrimmage", "Great Play Awareness"], weaknesses: ["Needs To Shed Blocks Better", "Needs To Gain 20lbs", "Might Not Fit All Schemes"]},
    {name: "Joshua Perry", position: "OLB", height: "6-4", weight: 253, rank: 6, bbRank: 46, school: "Ohio State", img: "http://www.thesportsbank.net/core/wp-content/uploads/2015/07/josh-perry-osu.jpg", schImg: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/84/2013_Ohio_State_Buckeyes_logo.svg/1040px-2013_Ohio_State_Buckeyes_logo.svg.png",  bio: "One of the stars of Ohio State's National Title run in the 2014 season, Bosa was a top high school recruit out of high school and has lived up to that high billing, leading the Buckeyes with 21 tackles for loss and 13.5 sacks as a sophomore. He is still developing his pass rush sequence and how to best use his gifts, but he has all the traits to be a top pick in the 2016 class and disruptive presence in the NFL.", strengths: ["Physical At Line Of Scrimmage", "Great Play Awareness"], weaknesses: ["Needs To Shed Blocks Better", "Needs To Gain 20lbs", "Might Not Fit All Schemes"]},
    {name: "Tyler Boyd", position: "WR", height: "6-2", weight: 200, rank: 6, bbRank: 47, school: "Pittsburgh", img: "http://img.bleacherreport.net/img/images/photos/003/478/457/hi-res-f6133a8a7fe5973bd905be8c71df40cb_crop_north.jpg?w=630&h=420&q=75", schImg: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b1/PittPanthersWordLogo.svg/1280px-PittPanthersWordLogo.svg.png",  bio: "One of the stars of Ohio State's National Title run in the 2014 season, Bosa was a top high school recruit out of high school and has lived up to that high billing, leading the Buckeyes with 21 tackles for loss and 13.5 sacks as a sophomore. He is still developing his pass rush sequence and how to best use his gifts, but he has all the traits to be a top pick in the 2016 class and disruptive presence in the NFL.", strengths: ["Physical At Line Of Scrimmage", "Great Play Awareness"], weaknesses: ["Needs To Shed Blocks Better", "Needs To Gain 20lbs", "Might Not Fit All Schemes"]},
    {name: "Jeremy Cash", position: "S ", height: "6-1", weight: 212, rank: 1, bbRank: 48, school: "Duke", img: "http://drdotcom.dukereport.netdna-cdn.com/wp-content/uploads/2015/09/DukeNCCU091215-23-e1445642406185.jpg", schImg: "https://www.helpustoreit.com/wp-content/uploads/2015/03/Duke.png",  bio: "One of the stars of Ohio State's National Title run in the 2014 season, Bosa was a top high school recruit out of high school and has lived up to that high billing, leading the Buckeyes with 21 tackles for loss and 13.5 sacks as a sophomore. He is still developing his pass rush sequence and how to best use his gifts, but he has all the traits to be a top pick in the 2016 class and disruptive presence in the NFL.", strengths: ["Physical At Line Of Scrimmage", "Great Play Awareness"], weaknesses: ["Needs To Shed Blocks Better", "Needs To Gain 20lbs", "Might Not Fit All Schemes"]},
    {name: "Vernon Butler", position: "DT", height: "6-4", weight: 325, rank: 8, bbRank: 49, school: "Louisiana Tech", img: "https://i.ytimg.com/vi/m8ihSBbNwdY/maxresdefault.jpg", schImg: "https://upload.wikimedia.org/wikipedia/en/thumb/c/cb/LA_Tech_Athletics_Logo.svg/1280px-LA_Tech_Athletics_Logo.svg.png",  bio: "One of the stars of Ohio State's National Title run in the 2014 season, Bosa was a top high school recruit out of high school and has lived up to that high billing, leading the Buckeyes with 21 tackles for loss and 13.5 sacks as a sophomore. He is still developing his pass rush sequence and how to best use his gifts, but he has all the traits to be a top pick in the 2016 class and disruptive presence in the NFL.", strengths: ["Physical At Line Of Scrimmage", "Great Play Awareness"], weaknesses: ["Needs To Shed Blocks Better", "Needs To Gain 20lbs", "Might Not Fit All Schemes"]},
    {name: "Vadal Alexander", position: "OG", height: "6-5", weight: 336, rank: 2, bbRank: 50, school: "LSU", img: "https://farm9.staticflickr.com/8689/17021691240_00a2e1a200_c.jpg", schImg: "https://sites01.lsu.edu/wp/riskmgt/files/2012/08/LSU-Gold1.png",  bio: "One of the stars of Ohio State's National Title run in the 2014 season, Bosa was a top high school recruit out of high school and has lived up to that high billing, leading the Buckeyes with 21 tackles for loss and 13.5 sacks as a sophomore. He is still developing his pass rush sequence and how to best use his gifts, but he has all the traits to be a top pick in the 2016 class and disruptive presence in the NFL.", strengths: ["Physical At Line Of Scrimmage", "Great Play Awareness"], weaknesses: ["Needs To Shed Blocks Better", "Needs To Gain 20lbs", "Might Not Fit All Schemes"]}
  ];

  user.save(function(err, result) {
    if(err) return next(err);
    res.send(result.createToken());
  });
});




module.exports = router;
